-- liquibase formatted sql

-- changeset NeelimaYamana:1695326498271-1
CREATE TABLE pdpstatistics (ID BIGINT NOT NULL, NAME VARCHAR(120) NOT NULL, VERSION VARCHAR(20) NOT NULL, PDPGROUPNAME VARCHAR(255) NULL, PDPSUBGROUPNAME VARCHAR(255) NULL, POLICYDEPLOYCOUNT BIGINT NULL, POLICYDEPLOYFAILCOUNT BIGINT NULL, POLICYDEPLOYSUCCESSCOUNT BIGINT NULL, POLICYEXECUTEDCOUNT BIGINT NULL, POLICYEXECUTEDFAILCOUNT BIGINT NULL, POLICYEXECUTEDSUCCESSCOUNT BIGINT NULL, TIMESTAMP datetime NULL);

-- changeset NeelimaYamana:1695326498271-2
INSERT INTO pdpstatistics (ID, NAME, VERSION, PDPGROUPNAME, PDPSUBGROUPNAME, POLICYDEPLOYCOUNT, POLICYDEPLOYFAILCOUNT, POLICYDEPLOYSUCCESSCOUNT, POLICYEXECUTEDCOUNT, POLICYEXECUTEDFAILCOUNT, POLICYEXECUTEDSUCCESSCOUNT, TIMESTAMP) VALUES (3, 'TestName', '1.0.0', 'TestGroup', 'TestSubGroup', 1, 1, 1, 1, 1, 1, '2023-09-21T15:56:14');

