
CREATE TABLE JpaPdpPolicyDeploymentAudit (
            ID BIGINT NOT NULL,
            NAME VARCHAR(120) NOT NULL,
            VERSION VARCHAR(20) NOT NULL,
            PDPGROUP VARCHAR(255) DEFAULT NULL NULL,
            PDPTYPE VARCHAR(255) DEFAULT NULL NULL,
            ACTION BIGINT DEFAULT NULL NULL,
            TIMESTAMP TIMESTAMP DEFAULT NULL NULL,
            CHANGEDBYUSER VARCHAR(255) DEFAULT NULL NULL,
            CONSTRAINT PK_PDPSTATISTICS PRIMARY KEY (ID, NAME, VERSION)
            );
