
CREATE TABLE PDPSTATISTICS (
                ID BIGINT NOT NULL,
                NAME VARCHAR(120) NOT NULL,
                VERSION VARCHAR(20) NOT NULL,
                PDPGROUPNAME VARCHAR(255) DEFAULT NULL,
                PDPSUBGROUPNAME VARCHAR(255) DEFAULT NULL,
                POLICYDEPLOYCOUNT BIGINT DEFAULT NULL,
                POLICYDEPLOYFAILCOUNT BIGINT DEFAULT NULL,
                POLICYDEPLOYSUCCESSCOUNT BIGINT DEFAULT NULL,
                POLICYEXECUTEDCOUNT BIGINT DEFAULT NULL,
                POLICYEXECUTEDFAILCOUNT BIGINT DEFAULT NULL,
                POLICYEXECUTEDSUCCESSCOUNT BIGINT DEFAULT NULL,
                TIMESTAMP TIMESTAMP DEFAULT NULL
            );
