
  INSERT INTO PDPSTATISTICS
            (ID, NAME, VERSION, PDPGROUPNAME, PDPSUBGROUPNAME, POLICYDEPLOYCOUNT, POLICYDEPLOYFAILCOUNT,
            POLICYDEPLOYSUCCESSCOUNT, POLICYEXECUTEDCOUNT, POLICYEXECUTEDFAILCOUNT,
            POLICYEXECUTEDSUCCESSCOUNT, TIMESTAMP)
            VALUES  (3, 'TestName', '1.0.0', 'TestGroup', 'TestSubGroup', 1, 1, 1, 1, 1, 1, now());


DELETE FROM PDPSTATISTICS WHERE ID=3;